// This file was generated by Prisma, and assumes you have installed the following:
// pnpm add --save-dev --save-exact @prisma/prisma7 dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/prisma7/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
